# Generated by Django 4.1.7 on 2023-03-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grafico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(choices=[('yes', 'SI'), ('no', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Ingrese la pregunta'),
        ),
    ]
