# Generated by Django 4.1.7 on 2023-03-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grafico', '0002_alter_answer_text_alter_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'No')], max_length=10),
        ),
    ]
